spring:
  application:
    name: backend-service
#  config:
#    import: "configserver:http://config:8888"
#  cloud:
#    config:
#      enabled: false
server:
  servlet:
    context-path: /backend-service/v1
  port: 8080
app:
  version: 1.0.0
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

